### PR TITLE
Fix UIColor alpha < 1 bug

### PR DESCRIPTION
**Pull request by jmkiley**
Addresses #125, but this time in the correct repo.

### CODE REVIEW

**Comment by chloekraw** [comment]
Don't think we've got test coverage of this part of the code base to where we want it to be, and we should do that before merging a fix

**Comment by jmkiley** [comment]
Makes sense! Will look into adding tests for this.

**Comment by jmkiley** [comment]
The code here currently uses the approach from https://github.com/mapbox/mapbox-gl-native/pull/16153#issuecomment-580416201, but it doesn't seem to be executed with the `fillColor` property. Going to go back through and revisit @1ec5's suggestions from here https://github.com/mapbox/mapbox-gl-native/pull/16223#discussion_r383694089

**Comment by nishant-karajgikar** [comment]
@jmkiley, what's the status of this PR?

**Comment by jmkiley** [comment]
I put a `UIView` with an alpha of 0.5 in the upper left corner to compare with the `MGLFillStyleLayer` that is also set to a `UIColor` with an alpha of 0.5.
| Current behavior on master: | Behavior in https://github.com/mapbox/mapbox-gl-native-ios/pull/215/commits/9f353e21db37b79f151b7f512cf954dbe9d009c0 | Behavior with separate UIColor method |
---|----------|-----
|  |  |  |

**Comment by nishant-karajgikar** [comment]
Closing in favor of #266

**Pull request closed without merging**
